
function apc_totaldata(line){

    let raw_data =apc_raw_dataRequest();
    let pyro_data =apc_pyro_dataRequest();

    return [
        {system:"生料磨系统",
            loop:[{loopname:"1#磨产量",
                loopdata:[
                    raw_data[line].loop[0].loopdata[0],
                    raw_data[line].loop[0].loopdata[1],
                    raw_data[line].loop[0].loopdata[2],
                    raw_data[line].loop[0].loopdata[3],
                    raw_data[line].loop[0].loopdata[4]
                ]},
                {loopname:"2#磨产量",
                    loopdata:[
                        raw_data[line].loop[1].loopdata[0],
                        raw_data[line].loop[1].loopdata[1],
                        raw_data[line].loop[1].loopdata[2],
                        raw_data[line].loop[1].loopdata[3],
                        raw_data[line].loop[1].loopdata[4]
                    ]}
            ]},
        {system:"回转窑系统",
            loop:[{loopname:"尾煤",
                loopdata:[
                    pyro_data[line].linedata[0].loop[0].loopdata[0],
                    pyro_data[line].linedata[0].loop[0].loopdata[1],
                    pyro_data[line].linedata[0].loop[0].loopdata[2],
                    pyro_data[line].linedata[0].loop[0].loopdata[3],
                    pyro_data[line].linedata[0].loop[0].loopdata[4]
                ]},
                {loopname:"头煤",
                    loopdata:[
                        pyro_data[line].linedata[0].loop[1].loopdata[0],
                        pyro_data[line].linedata[0].loop[1].loopdata[1],
                        pyro_data[line].linedata[0].loop[1].loopdata[2],
                        pyro_data[line].linedata[0].loop[1].loopdata[3]
                    ]},
                {loopname:"窑速",
                    loopdata:["手动",
                        pyro_data[line].linedata[0].loop[2].loopdata[1],
                        pyro_data[line].linedata[0].loop[2].loopdata[2],"0"]}
            ]},
        {system:"篦冷机系统",
            loop:[{loopname:"一段篦速",
                loopdata:[
                    pyro_data[line].linedata[1].loop[0].loopdata[0],
                    pyro_data[line].linedata[1].loop[0].loopdata[1],
                    pyro_data[line].linedata[1].loop[0].loopdata[2],
                    pyro_data[line].linedata[1].loop[0].loopdata[3],
                    pyro_data[line].linedata[1].loop[0].loopdata[4]
                ]},
                {loopname:"二段篦速",
                    loopdata:[
                        pyro_data[line].linedata[1].loop[1].loopdata[0],
                        pyro_data[line].linedata[1].loop[1].loopdata[1],
                        pyro_data[line].linedata[1].loop[1].loopdata[2],
                        pyro_data[line].linedata[1].loop[1].loopdata[3]
                    ]},
                {loopname:"头排",
                    loopdata:[
                        pyro_data[line].linedata[1].loop[2].loopdata[0],
                        pyro_data[line].linedata[1].loop[2].loopdata[1],
                        pyro_data[line].linedata[1].loop[2].loopdata[2],
                        pyro_data[line].linedata[1].loop[2].loopdata[3]
                    ]}
            ]},
        {system:"煤磨系统",
            loop:[{loopname:"1#磨产量",
                loopdata:[
                    pyro_data[line].linedata[2].loop[0].loopdata[0],
                    pyro_data[line].linedata[2].loop[0].loopdata[1],
                    pyro_data[line].linedata[2].loop[0].loopdata[2],
                    pyro_data[line].linedata[2].loop[0].loopdata[3]
                ]},
                {loopname:"1#磨温度",
                    loopdata:[
                        pyro_data[line].linedata[2].loop[1].loopdata[0],
                        pyro_data[line].linedata[2].loop[1].loopdata[1],
                        pyro_data[line].linedata[2].loop[1].loopdata[2],
                        pyro_data[line].linedata[2].loop[1].loopdata[3]
                    ]},
                {loopname:"2#磨产量",loopdata:[
                        pyro_data[line].linedata[2].loop[2].loopdata[0],
                        pyro_data[line].linedata[2].loop[2].loopdata[1],
                        pyro_data[line].linedata[2].loop[2].loopdata[2],
                        pyro_data[line].linedata[2].loop[2].loopdata[3]
                    ]},
                {loopname:"2#磨温度",loopdata:[
                        pyro_data[line].linedata[2].loop[3].loopdata[0],
                        pyro_data[line].linedata[2].loop[3].loopdata[1],
                        pyro_data[line].linedata[2].loop[3].loopdata[2],
                        pyro_data[line].linedata[2].loop[3].loopdata[3]
                    ]}
            ]},
        {system:"废气系统",
            loop:[{loopname:"尾排控制",
                loopdata:[
                    pyro_data[line].linedata[3].loop[0].loopdata[0],
                    pyro_data[line].linedata[3].loop[0].loopdata[1],
                    pyro_data[line].linedata[3].loop[0].loopdata[2],
                    pyro_data[line].linedata[3].loop[0].loopdata[3]
                ]},
                {loopname:"脱硝控制",
                    loopdata:[
                        pyro_data[line].linedata[3].loop[1].loopdata[0],
                        pyro_data[line].linedata[3].loop[1].loopdata[1],
                        pyro_data[line].linedata[3].loop[1].loopdata[2],
                        pyro_data[line].linedata[3].loop[1].loopdata[3]
                    ]}
            ]},
        {system:"余热系统",
            loop:[{loopname:"AQC高压水位",
                loopdata:[
                    pyro_data[line].linedata[4].loop[0].loopdata[0],
                    pyro_data[line].linedata[4].loop[0].loopdata[1],
                    pyro_data[line].linedata[4].loop[0].loopdata[2],
                    pyro_data[line].linedata[4].loop[0].loopdata[3]
                ]},
                {loopname:"AQC低压水位",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[1].loopdata[0],
                        pyro_data[line].linedata[4].loop[1].loopdata[1],
                        pyro_data[line].linedata[4].loop[1].loopdata[2],
                        pyro_data[line].linedata[4].loop[1].loopdata[3]
                    ]},
                {loopname:"SPA水位",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[2].loopdata[0],
                        pyro_data[line].linedata[4].loop[2].loopdata[1],
                        pyro_data[line].linedata[4].loop[2].loopdata[2],
                        pyro_data[line].linedata[4].loop[2].loopdata[3]
                    ]},
                {loopname:"SPB水位",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[3].loopdata[0],
                        pyro_data[line].linedata[4].loop[3].loopdata[1],
                        pyro_data[line].linedata[4].loop[3].loopdata[2],
                        pyro_data[line].linedata[4].loop[3].loopdata[3]
                    ]},
                {loopname:"汽机负荷",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[0].loopdata[0],
                        pyro_data[line].linedata[4].loop[0].loopdata[1]
                    ]}
            ]},
        {system:"水泥磨系统",
            loop:[{loopname:"1#磨产量",
                loopdata:[
                    pyro_data[line].linedata[5].loop[0].loopdata[0],
                    pyro_data[line].linedata[5].loop[0].loopdata[1],
                    pyro_data[line].linedata[5].loop[0].loopdata[2],
                    pyro_data[line].linedata[5].loop[0].loopdata[3],
                    pyro_data[line].linedata[5].loop[0].loopdata[4]
                ]},
                {loopname:"1#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[1].loopdata[0],
                        pyro_data[line].linedata[5].loop[1].loopdata[1],
                        pyro_data[line].linedata[5].loop[1].loopdata[2],
                        pyro_data[line].linedata[5].loop[1].loopdata[3]
                    ]},
                {loopname:"2#磨产量",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[2].loopdata[0],
                        pyro_data[line].linedata[5].loop[2].loopdata[1],
                        pyro_data[line].linedata[5].loop[2].loopdata[2],
                        pyro_data[line].linedata[5].loop[2].loopdata[3],
                        pyro_data[line].linedata[5].loop[2].loopdata[4]
                    ]},
                {loopname:"2#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[3].loopdata[0],
                        pyro_data[line].linedata[5].loop[3].loopdata[1],
                        pyro_data[line].linedata[5].loop[3].loopdata[2],
                        pyro_data[line].linedata[5].loop[3].loopdata[3]
                    ]},
                {loopname:"3#磨产量",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[4].loopdata[0],
                        pyro_data[line].linedata[5].loop[4].loopdata[1],
                        pyro_data[line].linedata[5].loop[4].loopdata[2],
                        pyro_data[line].linedata[5].loop[4].loopdata[3],
                        pyro_data[line].linedata[5].loop[4].loopdata[4]
                    ]},
                {loopname:"3#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[5].loopdata[0],
                        pyro_data[line].linedata[5].loop[5].loopdata[1],
                        pyro_data[line].linedata[5].loop[5].loopdata[2],
                        pyro_data[line].linedata[5].loop[5].loopdata[3]
                    ]},
                {loopname:"4#磨产量",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[6].loopdata[0],
                        pyro_data[line].linedata[5].loop[6].loopdata[1],
                        pyro_data[line].linedata[5].loop[6].loopdata[2],
                        pyro_data[line].linedata[5].loop[6].loopdata[3],
                        pyro_data[line].linedata[5].loop[6].loopdata[4]
                    ]},
                {loopname:"4#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[7].loopdata[0],
                        pyro_data[line].linedata[5].loop[7].loopdata[1],
                        pyro_data[line].linedata[5].loop[7].loopdata[2],
                        pyro_data[line].linedata[5].loop[7].loopdata[3]
                    ]}
            ]}
    ];

}



function apc_simpledata(line){

    let raw_data =apc_raw_dataRequest();
    let pyro_data =apc_pyro_dataRequest();

    return [
        {system:"生料磨系统",
            loop:[{loopname:"1#磨产量",
                loopdata:[
                    raw_data[line].loop[0].loopdata[0],
                    raw_data[line].loop[0].loopdata[4]
                ]},
                {loopname:"2#磨产量",
                    loopdata:[
                        raw_data[line].loop[1].loopdata[0],
                        raw_data[line].loop[1].loopdata[4]
                    ]}
            ]},
        {system:"回转窑系统",
            loop:[{loopname:"尾煤",
                loopdata:[
                    pyro_data[line].linedata[0].loop[0].loopdata[0],
                    pyro_data[line].linedata[0].loop[0].loopdata[4]
                ]},
                {loopname:"头煤",
                    loopdata:[
                        pyro_data[line].linedata[0].loop[1].loopdata[0],
                        pyro_data[line].linedata[0].loop[1].loopdata[3]
                    ]},
                {loopname:"窑速",
                    loopdata:["手动", "0"]}
            ]},
        {system:"篦冷机系统",
            loop:[{loopname:"一段篦速",
                loopdata:[
                    pyro_data[line].linedata[1].loop[0].loopdata[0],
                    pyro_data[line].linedata[1].loop[0].loopdata[4]
                ]},
                {loopname:"二段篦速",
                    loopdata:[
                        pyro_data[line].linedata[1].loop[1].loopdata[0],
                        pyro_data[line].linedata[1].loop[1].loopdata[3]
                    ]},
                {loopname:"头排",
                    loopdata:[
                        pyro_data[line].linedata[1].loop[2].loopdata[0],
                        pyro_data[line].linedata[1].loop[2].loopdata[3]
                    ]}
            ]},
        {system:"煤磨系统",
            loop:[{loopname:"1#磨产量",
                loopdata:[
                    pyro_data[line].linedata[2].loop[0].loopdata[0],
                    pyro_data[line].linedata[2].loop[0].loopdata[3]
                ]},
                {loopname:"1#磨温度",
                    loopdata:[
                        pyro_data[line].linedata[2].loop[1].loopdata[0],
                        pyro_data[line].linedata[2].loop[1].loopdata[3]
                    ]},
                {loopname:"2#磨产量",loopdata:[
                        pyro_data[line].linedata[2].loop[2].loopdata[0],
                        pyro_data[line].linedata[2].loop[2].loopdata[3]
                    ]},
                {loopname:"2#磨温度",loopdata:[
                        pyro_data[line].linedata[2].loop[3].loopdata[0],
                        pyro_data[line].linedata[2].loop[3].loopdata[3]
                    ]}
            ]},
        {system:"废气系统",
            loop:[{loopname:"尾排控制",
                loopdata:[
                    pyro_data[line].linedata[3].loop[0].loopdata[0],
                    pyro_data[line].linedata[3].loop[0].loopdata[3]
                ]},
                {loopname:"脱硝控制",
                    loopdata:[
                        pyro_data[line].linedata[3].loop[1].loopdata[0],
                        pyro_data[line].linedata[3].loop[1].loopdata[3]
                    ]}
            ]},
        {system:"余热系统",
            loop:[{loopname:"AQC高压水位",
                loopdata:[
                    pyro_data[line].linedata[4].loop[0].loopdata[0],
                    pyro_data[line].linedata[4].loop[0].loopdata[3]
                ]},
                {loopname:"AQC低压水位",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[1].loopdata[0],
                        pyro_data[line].linedata[4].loop[1].loopdata[3]
                    ]},
                {loopname:"SPA水位",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[2].loopdata[0],
                        pyro_data[line].linedata[4].loop[2].loopdata[3]
                    ]},
                {loopname:"SPB水位",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[3].loopdata[0],
                        pyro_data[line].linedata[4].loop[3].loopdata[3]
                    ]},
                {loopname:"汽机负荷",
                    loopdata:[
                        pyro_data[line].linedata[4].loop[4].loopdata[0],
                        pyro_data[line].linedata[4].loop[4].loopdata[1]
                    ]}
            ]},
        {system:"水泥磨系统",
            loop:[{loopname:"1#磨产量",
                loopdata:[
                    pyro_data[line].linedata[5].loop[0].loopdata[0],
                    pyro_data[line].linedata[5].loop[0].loopdata[4]
                ]},
                {loopname:"1#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[1].loopdata[0],
                        pyro_data[line].linedata[5].loop[1].loopdata[3]
                    ]},
                {loopname:"2#磨产量",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[2].loopdata[0],
                        pyro_data[line].linedata[5].loop[2].loopdata[4]
                    ]},
                {loopname:"2#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[3].loopdata[0],
                        pyro_data[line].linedata[5].loop[3].loopdata[3]
                    ]},
                {loopname:"3#磨产量",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[4].loopdata[0],
                        pyro_data[line].linedata[5].loop[4].loopdata[4]
                    ]},
                {loopname:"3#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[5].loopdata[0],
                        pyro_data[line].linedata[5].loop[5].loopdata[3]
                    ]},
                {loopname:"4#磨产量",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[6].loopdata[0],
                        pyro_data[line].linedata[5].loop[6].loopdata[4]
                    ]},
                {loopname:"4#下料阀",
                    loopdata:[
                        pyro_data[line].linedata[5].loop[7].loopdata[0],
                        pyro_data[line].linedata[5].loop[7].loopdata[3]
                    ]}
            ]}
    ];

}
