package Bap.Device;


/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import Bap.BapDevicewsdl.FaultInfoRelevantService;
import Bap.BapDevicewsdl.FaultInfoRelevantService_FaultInfoRelevantServiceImplPort_Client;
import org.apache.log4j.Logger;

import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-11T18:11:16.252+08:00
 * Generated source version: 3.3.6
 *
 */
public final class BapDeviceAlarm {
    private static Logger logger = Logger.getLogger(BapDeviceAlarm.class);
    private static final QName SERVICE_NAME = new QName("http://ws.supcon.com", "FaultInfoRelevantServiceImplService");
    URL url;
    public BapDeviceAlarm(URL url) {
        this.url=url;
    }


    public  String PushAlarmMessage( java.lang.String eamCode,
            java.lang.String sourceType,
            java.lang.String faultInfoType ,
            java.lang.String priority ,
            java.lang.String findStaffCode,
            java.lang.String describe,
            java.lang.Long findTime){
        FaultInfoRelevantService_FaultInfoRelevantServiceImplPort_Client ss = new FaultInfoRelevantService_FaultInfoRelevantServiceImplPort_Client(url);
        FaultInfoRelevantService port = null;
        try {
            port = ss.getSerice();
        } catch (Exception e) {
           logger.error(e);
        }
        java.lang.String _genFaultInfoByItemNo__return = port.genFaultInfoByItemNo(eamCode, sourceType, faultInfoType, priority,findStaffCode,describe,findTime);
            return _genFaultInfoByItemNo__return;
    }



}
