package Bap.BapDevicewsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-29T15:37:18.770+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "FaultInfoRelevantServiceImplService",
                  wsdlLocation = "file:/E:/ProcessReport_High/src/Bap/BapDevicewsdl/faultInfoRelevantService.wsdl",
                  targetNamespace = "http://ws.supcon.com")
public class FaultInfoRelevantServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.supcon.com", "FaultInfoRelevantServiceImplService");
    public final static QName FaultInfoRelevantServiceImplPort = new QName("http://ws.supcon.com", "FaultInfoRelevantServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/ProcessReport_High/src/Bap/BapDevicewsdl/faultInfoRelevantService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FaultInfoRelevantServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/ProcessReport_High/src/Bap/BapDevicewsdl/faultInfoRelevantService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FaultInfoRelevantServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FaultInfoRelevantServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FaultInfoRelevantServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FaultInfoRelevantServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FaultInfoRelevantServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FaultInfoRelevantServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FaultInfoRelevantService
     */
    @WebEndpoint(name = "FaultInfoRelevantServiceImplPort")
    public FaultInfoRelevantService getFaultInfoRelevantServiceImplPort() {
        return super.getPort(FaultInfoRelevantServiceImplPort, FaultInfoRelevantService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FaultInfoRelevantService
     */
    @WebEndpoint(name = "FaultInfoRelevantServiceImplPort")
    public FaultInfoRelevantService getFaultInfoRelevantServiceImplPort(WebServiceFeature... features) {
        return super.getPort(FaultInfoRelevantServiceImplPort, FaultInfoRelevantService.class, features);
    }

}
