
package Bap.BapDevicewsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-29T15:37:18.307+08:00
 * Generated source version: 3.3.6
 *
 */
public final class FaultInfoRelevantService_FaultInfoRelevantServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.supcon.com", "FaultInfoRelevantServiceImplService");
    URL url;
    public FaultInfoRelevantService_FaultInfoRelevantServiceImplPort_Client(URL url) {
        this.url= url;
    }

    public  FaultInfoRelevantService  getSerice() throws java.lang.Exception {
//        URL wsdlURL = FaultInfoRelevantServiceImplService.WSDL_LOCATION;

        FaultInfoRelevantServiceImplService ss = new FaultInfoRelevantServiceImplService(url, SERVICE_NAME);
        return  ss.getFaultInfoRelevantServiceImplPort();

    }

}
